spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false
  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/chat_websocket?useSSL=false&serverTimezone=UTC
    username: root
    password: happyjeong97
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 10000
      max-lifetime: 2000000
      connection-timeout: 30000
      pool-name: SpringHikariCP
mybatis:
  mapper-locations: classpath*:mappers/**/*.xml

